Update cloning.md
- Updated the image for using the Fedora-Cloud-Base-33-1.2.x86_64.raw.xz since the image https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz is not available more or at least it's returning an HTTP response code 404:

~~~
# wget https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz
--2021-01-26 08:42:31--  https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz
Resolving download.fedoraproject.org (download.fedoraproject.org)... 140.211.169.196, 152.19.134.142, 8.43.85.67, ...
Connecting to download.fedoraproject.org (download.fedoraproject.org)|140.211.169.196|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-26 08:42:32 ERROR 404: Not Found.
~~~

At the same time, the wget command could return the error below:

~~~
# wget https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
--2021-01-26 08:48:01--  https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
Resolving download.fedoraproject.org (download.fedoraproject.org)... 8.43.85.73, 209.132.190.2, 152.19.134.198, ...
Connecting to download.fedoraproject.org (download.fedoraproject.org)|8.43.85.73|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mirror.us-midwest-1.nexcess.net/fedora/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz [following]
--2021-01-26 08:48:02--  https://mirror.us-midwest-1.nexcess.net/fedora/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
Resolving mirror.us-midwest-1.nexcess.net (mirror.us-midwest-1.nexcess.net)... 208.69.120.125
Connecting to mirror.us-midwest-1.nexcess.net (mirror.us-midwest-1.nexcess.net)|208.69.120.125|:443... connected.
ERROR: The certificate of ‘mirror.us-midwest-1.nexcess.net’ is not trusted.
ERROR: The certificate of ‘mirror.us-midwest-1.nexcess.net’ has expired.
~~~

Then, it was modified for using the option `--no-dns-cache` like this for skipping the error:

~~~
 $ wget --no-dns-cache https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
~~~


- Updated all the references
 - from fc-31to fc-33
 - from fc31 to fc-33
 - from Fedora 31 to Fedora 33